### ISSUE TITLE
BiocCheck issues

### ISSUE THREAD

**Issue by GuangchuangYu** [YuLab-SMU/ggtreeSpace#3]
goodpractice输出：
```
 ✖ use '<-' for assignment instead of '='. '<-' is the standard, and R
    users and developers are used it and it is easier to read your code
    for them if you use '<-'.

    R\phylospm.R:68:5
    R\phylospm.R:70:7

  ✖ avoid long code lines, it is bad for readability. Also, many people
    prefer editor windows that are about 80 characters wide. Try make
    your lines shorter than 80 characters

    R\geom_tsheatmap.R:38:81
    R\phylospm.R:8:81
    R\phylospm.R:30:81
    R\phylospm.R:32:81
    R\phylospm.R:33:81
    ... and 8 more lines

  ✖ avoid 'T' and 'F', as they are just variables which are set to the
    logicals 'TRUE' and 'FALSE' by default, but are not reserved words
    and hence can be overwritten by the user.  Hence, one should always
    use 'TRUE' and 'FALSE' for the logicals.

    R/phylospm.R:NA:NA
```

BiocCheck输出：

```
* Installing package...
* Checking for deprecated package usage...
adding rname 'https://bioconductor.org/checkResults/3.18/bioc-LATEST/meat-index.dcf'
adding rname 'https://bioconductor.org/checkResults/3.19/bioc-LATEST/meat-index.dcf'
* Checking for remote package usage...
* Checking for 'LazyData: true' usage...
* Checking version number...
* Checking for version number mismatch...
* Checking version number validity...
    * ERROR: Invalid package Version, see
      https://contributions.bioconductor.org/versionnum.html
* Checking R version dependency...
* Checking package size...
* Checking individual file sizes...
* Checking biocViews...
* Checking that biocViews are present...
    * ERROR: No biocViews terms found.
Search 'biocViews' at https://contributions.bioconductor.org
* Checking build system compatibility...
* Checking for blank lines in DESCRIPTION...
* Checking if DESCRIPTION is well formatted...
* Checking for proper Description: field...
    * WARNING: Description field in the DESCRIPTION file is too concise
* Checking for whitespace in DESCRIPTION field names...
* Checking that Package field matches directory/tarball name...
* Checking for Version field...
* Checking for valid maintainer...
    * NOTE: Consider adding the maintainer's ORCID iD in 'Authors@R'
      with 'comment=c(ORCID="...")'
* Checking License: for restrictive use...
* Checking for recommeded fields in DESCRIPTION...
    * NOTE: Provide "URL", "BugReports" field(s) in DESCRIPTION
* Checking for pinned package versions...
* Checking DESCRIPTION/NAMESPACE consistency...
    * WARNING: Import grid in DESCRIPTION as well as NAMESPACE.
* Checking .Rbuildignore...
* Checking for stray BiocCheck output folders...
* Checking vignette directory...
    * ERROR: No 'vignettes' directory.
* Checking package installation calls in R code...
* Checking for library/require of ggtreeSpace...
* Checking coding practice...
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
    * NOTE: Avoid 'cat' and 'print' outside of 'show' methods
    * NOTE: Avoid using '=' for assignment and use '<-' instead
    * WARNING: Avoid T/F variables; If logical, use TRUE/FALSE
* Checking parsed R code in R directory, examples, vignettes...
    * NOTE: Avoid 'suppressWarnings'/'*Messages' if possible (found 3
      times)
* Checking function lengths...
    * NOTE: The recommended function length is 50 lines or less. There
      is 1 function greater than 50 lines.
* Checking man page documentation...
    * WARNING: Empty or missing \value sections found in man pages.
    * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples.
* Checking package NEWS...
    * NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.
* Checking unit tests...
    * NOTE: Consider adding unit tests. We strongly encourage them. See
      https://contributions.bioconductor.org/tests.html
* Checking skip_on_bioc() in tests...
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * NOTE: Consider shorter lines; 15 lines (2%) are > 80 characters
      long.
    * NOTE: Consider multiples of 4 spaces for line indents; 168 lines
      (25%) are not.
    See https://contributions.bioconductor.org/r-code.html
    See styler package: https://cran.r-project.org/package=styler as
      described in the BiocCheck vignette.
* Checking if package already exists in CRAN...
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://mirrors.ustc.edu.cn/CRAN/
* Checking for bioc-devel mailing list subscription...
    * NOTE: Cannot determine whether maintainer is subscribed to the
      Bioc-Devel mailing list (requires admin credentials). Subscribe
      here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
* Checking for support site registration...
    * ERROR: Unable to find your email in the Support Site: HTTP 404
      Not Found.

─ BiocCheck results ──
5 ERRORS | 4 WARNINGS | 12 NOTES

See the ggtreeSpace.BiocCheck folder and run
    browseVignettes(package = 'BiocCheck')
for details.
```

@SanL20 解决这些问题，然后这个包才好提交到Bioconductor上。

**Comment by SanL20** [comment]
好的老师。我近期解决一下问题，顺便把新的版本pr上去。
&nbsp;


San
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Guangchuang ***@***.***&gt;; 
发送时间: 2024年3月16日(星期六) 晚上11:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: [YuLab-SMU/ggtreeSpace] BiocCheck issues (Issue #3)





 
goodpractice输出：
  ✖ use '<-' for assignment instead of '='. '<-' is the standard, and R     users and developers are used it and it is easier to read your code     for them if you use '<-'.     R\phylospm.R:68:5     R\phylospm.R:70:7   ✖ avoid long code lines, it is bad for readability. Also, many people     prefer editor windows that are about 80 characters wide. Try make     your lines shorter than 80 characters     R\geom_tsheatmap.R:38:81     R\phylospm.R:8:81     R\phylospm.R:30:81     R\phylospm.R:32:81     R\phylospm.R:33:81     ... and 8 more lines   ✖ avoid 'T' and 'F', as they are just variables which are set to the     logicals 'TRUE' and 'FALSE' by default, but are not reserved words     and hence can be overwritten by the user.  Hence, one should always     use 'TRUE' and 'FALSE' for the logicals.     R/phylospm.R:NA:NA  
BiocCheck输出：
 * Installing package... * Checking for deprecated package usage... adding rname 'https://bioconductor.org/checkResults/3.18/bioc-LATEST/meat-index.dcf' adding rname 'https://bioconductor.org/checkResults/3.19/bioc-LATEST/meat-index.dcf' * Checking for remote package usage... * Checking for 'LazyData: true' usage... * Checking version number... * Checking for version number mismatch... * Checking version number validity...     * ERROR: Invalid package Version, see       https://contributions.bioconductor.org/versionnum.html * Checking R version dependency... * Checking package size... * Checking individual file sizes... * Checking biocViews... * Checking that biocViews are present...     * ERROR: No biocViews terms found. Search 'biocViews' at https://contributions.bioconductor.org * Checking build system compatibility... * Checking for blank lines in DESCRIPTION... * Checking if DESCRIPTION is well formatted... * Checking for proper Description: field...     * WARNING: Description field in the DESCRIPTION file is too concise * Checking for whitespace in DESCRIPTION field names... * Checking that Package field matches directory/tarball name... * Checking for Version field... * Checking for valid maintainer...     * NOTE: Consider adding the maintainer's ORCID iD in ***@***.***'       with 'comment=c(ORCID="...")' * Checking License: for restrictive use... * Checking for recommeded fields in DESCRIPTION...     * NOTE: Provide "URL", "BugReports" field(s) in DESCRIPTION * Checking for pinned package versions... * Checking DESCRIPTION/NAMESPACE consistency...     * WARNING: Import grid in DESCRIPTION as well as NAMESPACE. * Checking .Rbuildignore... * Checking for stray BiocCheck output folders... * Checking vignette directory...     * ERROR: No 'vignettes' directory. * Checking package installation calls in R code... * Checking for library/require of ggtreeSpace... * Checking coding practice...     * NOTE: Avoid 1:...; use seq_len() or seq_along()     * NOTE: Avoid 'cat' and 'print' outside of 'show' methods     * NOTE: Avoid using '=' for assignment and use '<-' instead     * WARNING: Avoid T/F variables; If logical, use TRUE/FALSE * Checking parsed R code in R directory, examples, vignettes...     * NOTE: Avoid 'suppressWarnings'/'*Messages' if possible (found 3       times) * Checking function lengths...     * NOTE: The recommended function length is 50 lines or less. There       is 1 function greater than 50 lines. * Checking man page documentation...     * WARNING: Empty or missing \value sections found in man pages.     * ERROR: At least 80% of man pages documenting exported objects       must have runnable examples. * Checking package NEWS...     * NOTE: Consider adding a NEWS file, so your package news will be       included in Bioconductor release announcements. * Checking unit tests...     * NOTE: Consider adding unit tests. We strongly encourage them. See       https://contributions.bioconductor.org/tests.html * Checking skip_on_bioc() in tests... * Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,   and vignette source...     * NOTE: Consider shorter lines; 15 lines (2%) are &gt; 80 characters       long.     * NOTE: Consider multiples of 4 spaces for line indents; 168 lines       (25%) are not.     See https://contributions.bioconductor.org/r-code.html     See styler package: https://cran.r-project.org/package=styler as       described in the BiocCheck vignette. * Checking if package already exists in CRAN... 'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for details. Replacement repositories:     CRAN: https://mirrors.ustc.edu.cn/CRAN/ * Checking for bioc-devel mailing list subscription...     * NOTE: Cannot determine whether maintainer is subscribed to the       Bioc-Devel mailing list (requires admin credentials). Subscribe       here: https://stat.ethz.ch/mailman/listinfo/bioc-devel * Checking for support site registration...     * ERROR: Unable to find your email in the Support Site: HTTP 404       Not Found. ─ BiocCheck results ── 5 ERRORS | 4 WARNINGS | 12 NOTES See the ggtreeSpace.BiocCheck folder and run     browseVignettes(package = 'BiocCheck') for details.  
@SanL20 解决这些问题，然后这个包才好提交到Bioconductor上。
